import { createRouter, createWebHistory } from 'vue-router'
import { useAuthStore } from '../stores/auth.js'

const ROUTE_PERMISSIONS = {
  pos: 'pos',
  products: 'products',
  'product-detail': 'products',
  categories: 'products',
  barcodes: 'products',
  'product-types': 'products',
  attributes: 'products',
  'batch-numbers': 'inventory',
  'serial-numbers': 'inventory',
  inventory: 'inventory',
  'inventory-counts': 'inventory',
  warehouses: 'warehouse',
  'stock-movements': 'inventory',
  'stock-adjustments': 'inventory',
  'inventory-overview': 'inventory',
  'inventory-reports': 'inventory',
  'inventory-config': 'inventory',
  'pick-lists': 'warehouse',
  'pick-list-detail': 'warehouse',
  leads: 'crm',
  opportunities: 'crm',
  customers: 'customers',
  'customer-detail': 'customers',
  sales: 'sales',
  'sales-detail': 'sales',
  'sales-quotations': 'sales',
  'sales-quotation-detail': 'sales',
  'sales-deliveries': 'sales',
  'sales-returns': 'sales',
  'sales-price-lists': 'sales',
  'sales-tax-rates': 'sales',
  finance: 'finance',
  'invoice-detail': 'finance',
  'chart-of-accounts': 'finance',
  'journal-entries': 'finance',
  payments: 'finance',
  'payment-terms': 'finance',
  'payment-methods': 'finance',
  suppliers: 'suppliers',
  'purchasing-requisitions': 'purchasing',
  'purchasing-rfqs': 'purchasing',
  'purchasing-order-detail': 'purchasing',
  'purchasing-returns': 'purchasing',
  purchasing: 'purchasing',
  'goods-receipt': 'warehouse',
  admin: 'admin',
  modules: 'admin',
  subscription: 'admin',
  migration: 'admin',
  'audit-log': 'admin',
  'scheduled-tasks': 'admin',
  workflow: 'admin',
  departments: 'hr',
  designations: 'hr',
  employees: 'hr',
  'hr-leaves': 'hr',
  'hr-attendance': 'hr',
  'hr-payroll': 'hr',
  'hr-timesheets': 'hr',
  'hr-jobs': 'hr',
  'hr-candidates': 'hr',
  projects: 'projects',
  'project-tasks': 'projects',
  'project-milestones': 'projects',
  contracts: 'projects',
  documents: 'projects',
  'maintenance-assets': 'maintenance',
  'maintenance-schedules': 'maintenance',
  'maintenance-work-orders': 'maintenance',
  'bi-kpis': 'bi',
  'bi-dashboards': 'bi',
  'bi-view': 'bi',
  'bi-reports': 'bi',
  'bi-forecasting': 'bi',
  'mfg-bom': 'manufacturing',
  'mfg-orders': 'manufacturing',
  'mfg-qc': 'manufacturing',
  'mfg-shopfloor': 'manufacturing',
  'production-plans': 'planning',
  'resource-planning': 'planning',
  integrations: 'integrations',
  'integrations-ecommerce': 'integrations',
  'integrations-api': 'integrations',
  'enterprise-tenants': 'admin',
  'enterprise-governance': 'admin',
  'enterprise-platform': 'admin',
}

const routes = [
  { path: '/login', name: 'login', component: () => import('../views/auth/LoginView.vue') },
  { path: '/signup', name: 'signup', component: () => import('../views/auth/SignUpView.vue') },
  { path: '/landing', name: 'landing', component: () => import('../views/landing/LandingView.vue') },
  { path: '/privacy', name: 'privacy', component: () => import('../views/legal/PrivacyView.vue') },
  { path: '/terms', name: 'terms', component: () => import('../views/legal/TermsView.vue') },
  {
    path: '/',
    component: () => import('../layouts/AppLayout.vue'),
    children: [
      { path: '', name: 'home', meta: { requiresAuth: true }, component: () => import('../views/home/HomeView.vue') },
      { path: 'dashboard', name: 'dashboard', meta: { requiresAuth: true }, component: () => import('../views/dashboard/DashboardView.vue') },
      { path: 'pos', name: 'pos', meta: { requiresAuth: true }, component: () => import('../views/pos/POSView.vue') },
      { path: 'products', name: 'products', meta: { requiresAuth: true }, component: () => import('../views/products/ProductsView.vue') },
      { path: 'products/:id', name: 'product-detail', meta: { requiresAuth: true }, component: () => import('../views/products/ProductDetailView.vue') },
      { path: 'categories', name: 'categories', meta: { requiresAuth: true }, component: () => import('../views/categories/CategoriesView.vue') },
      { path: 'customers', name: 'customers', meta: { requiresAuth: true }, component: () => import('../views/customers/CustomersView.vue') },
      { path: 'customers/:id', name: 'customer-detail', meta: { requiresAuth: true }, component: () => import('../views/customers/CustomerDetailView.vue') },
      { path: 'suppliers', name: 'suppliers', meta: { requiresAuth: true }, component: () => import('../views/suppliers/SuppliersView.vue') },
      { path: 'sales', name: 'sales', meta: { requiresAuth: true }, component: () => import('../views/sales/SalesView.vue') },
      { path: 'sales/:id', name: 'sales-detail', meta: { requiresAuth: true }, component: () => import('../views/sales/OrderDetailView.vue') },
      { path: 'sales/quotations', name: 'sales-quotations', meta: { requiresAuth: true }, component: () => import('../views/sales/QuotationsView.vue') },
      { path: 'sales/quotations/:id', name: 'sales-quotation-detail', meta: { requiresAuth: true }, component: () => import('../views/sales/QuotationDetailView.vue') },
      { path: 'sales/deliveries', name: 'sales-deliveries', meta: { requiresAuth: true }, component: () => import('../views/sales/DeliveriesView.vue') },
      { path: 'sales/returns', name: 'sales-returns', meta: { requiresAuth: true }, component: () => import('../views/sales/SalesReturnsView.vue') },
      { path: 'sales/price-lists', name: 'sales-price-lists', meta: { requiresAuth: true }, component: () => import('../views/sales/PriceListsView.vue') },
      { path: 'sales/tax-rates', name: 'sales-tax-rates', meta: { requiresAuth: true }, component: () => import('../views/sales/TaxRatesView.vue') },
      { path: 'purchasing', name: 'purchasing', meta: { requiresAuth: true }, component: () => import('../views/purchasing/PurchasingView.vue') },
      { path: 'purchasing/requisitions', name: 'purchasing-requisitions', meta: { requiresAuth: true }, component: () => import('../views/purchasing/PurchaseRequisitionsView.vue') },
      { path: 'purchasing/rfqs', name: 'purchasing-rfqs', meta: { requiresAuth: true }, component: () => import('../views/purchasing/RFQView.vue') },
      { path: 'purchasing/orders/:id', name: 'purchasing-order-detail', meta: { requiresAuth: true }, component: () => import('../views/purchasing/PurchaseOrdersDetailView.vue') },
      { path: 'purchasing/returns', name: 'purchasing-returns', meta: { requiresAuth: true }, component: () => import('../views/purchasing/PurchaseReturnsView.vue') },
      { path: 'inventory', name: 'inventory', meta: { requiresAuth: true }, component: () => import('../views/inventory/InventoryView.vue') },
      { path: 'inventory/overview', name: 'inventory-overview', meta: { requiresAuth: true }, component: () => import('../views/inventory/InventoryOverviewView.vue') },
      { path: 'inventory/reports', name: 'inventory-reports', meta: { requiresAuth: true }, component: () => import('../views/inventory/InventoryReportsView.vue') },
      { path: 'inventory/config', name: 'inventory-config', meta: { requiresAuth: true }, component: () => import('../views/inventory/InventoryConfigView.vue') },
      { path: 'inventory/counts', name: 'inventory-counts', meta: { requiresAuth: true }, component: () => import('../views/inventory-counts/InventoryCountsView.vue') },
      { path: 'warehouse', meta: { requiresAuth: true }, redirect: { name: 'warehouses' } },
      { path: 'finance', name: 'finance', meta: { requiresAuth: true }, component: () => import('../views/finance/FinanceView.vue') },
      { path: 'finance/:id', name: 'invoice-detail', meta: { requiresAuth: true }, component: () => import('../views/finance/InvoiceDetailView.vue') },
      { path: 'admin', name: 'admin', meta: { requiresAuth: true }, component: () => import('../views/admin/AdminView.vue') },
      { path: 'modules', name: 'modules', meta: { requiresAuth: true }, component: () => import('../views/admin/ModuleManagerView.vue') },
      { path: 'settings', name: 'settings', meta: { requiresAuth: true }, component: () => import('../views/settings/SettingsView.vue') },
      { path: 'admin/subscription', name: 'subscription', meta: { requiresAuth: true }, component: () => import('../views/admin/SubscriptionView.vue') },
      { path: 'uom', name: 'uom', meta: { requiresAuth: true }, component: () => import('../views/uom/UOMView.vue') },
      { path: 'uom-conversions', name: 'uom-conversions', meta: { requiresAuth: true }, component: () => import('../views/uom-conversions/UOMConvView.vue') },
      { path: 'barcodes', name: 'barcodes', meta: { requiresAuth: true }, component: () => import('../views/barcodes/BarcodesView.vue') },
      { path: 'product-types', name: 'product-types', meta: { requiresAuth: true }, component: () => import('../views/product-types/ProductTypesView.vue') },
      { path: 'attributes', name: 'attributes', meta: { requiresAuth: true }, component: () => import('../views/attributes/AttributesView.vue') },
      { path: 'stock-movements', name: 'stock-movements', meta: { requiresAuth: true }, component: () => import('../views/stock-movements/StockMovementsView.vue') },
      { path: 'stock-adjustments', name: 'stock-adjustments', meta: { requiresAuth: true }, component: () => import('../views/adjustments/AdjustmentsView.vue') },
      { path: 'warehouses', name: 'warehouses', meta: { requiresAuth: true }, component: () => import('../views/warehouses/WarehouseView.vue') },
      { path: 'inventory/batch-numbers', name: 'batch-numbers', meta: { requiresAuth: true }, component: () => import('../views/inventory/BatchNumbersView.vue') },
      { path: 'inventory/serial-numbers', name: 'serial-numbers', meta: { requiresAuth: true }, component: () => import('../views/inventory/SerialNumbersView.vue') },
      { path: 'chart-of-accounts', name: 'chart-of-accounts', meta: { requiresAuth: true }, component: () => import('../views/chart-of-accounts/ChartOfAccountsView.vue') },
      { path: 'journal-entries', name: 'journal-entries', meta: { requiresAuth: true }, component: () => import('../views/journal-entries/JournalEntriesView.vue') },
      { path: 'payments', name: 'payments', meta: { requiresAuth: true }, component: () => import('../views/payments/PaymentsView.vue') },
      { path: 'payment-terms', name: 'payment-terms', meta: { requiresAuth: true }, component: () => import('../views/payment-terms/PaymentTermsView.vue') },
      { path: 'payment-methods', name: 'payment-methods', meta: { requiresAuth: true }, component: () => import('../views/payment-methods/PaymentMethodsView.vue') },
      { path: 'crm/leads', name: 'leads', meta: { requiresAuth: true }, component: () => import('../views/crm/LeadsView.vue') },
      { path: 'crm/opportunities', name: 'opportunities', meta: { requiresAuth: true }, component: () => import('../views/crm/OpportunitiesView.vue') },
      { path: 'purchasing/goods-receipt', name: 'goods-receipt', meta: { requiresAuth: true }, component: () => import('../views/purchasing/GoodsReceiptView.vue') },
      { path: 'warehouse/pick-lists', name: 'pick-lists', meta: { requiresAuth: true }, component: () => import('../views/warehouse/PickListsView.vue') },
      { path: 'warehouse/pick-lists/:id', name: 'pick-list-detail', meta: { requiresAuth: true }, component: () => import('../views/warehouse/PickListDetailView.vue') },
      { path: 'migration', name: 'migration', meta: { requiresAuth: true }, component: () => import('../views/migration/MigrateView.vue') },
      { path: 'admin/audit-log', name: 'audit-log', meta: { requiresAuth: true }, component: () => import('../views/admin/AuditLogView.vue') },
      { path: 'admin/scheduled-tasks', name: 'scheduled-tasks', meta: { requiresAuth: true }, component: () => import('../views/admin/ScheduledTasksView.vue') },
      { path: 'admin/workflow', name: 'workflow', meta: { requiresAuth: true }, component: () => import('../views/admin/WorkflowView.vue') },
      { path: 'admin/tenants', name: 'enterprise-tenants', meta: { requiresAuth: true }, component: () => import('../views/admin/TenantsView.vue') },
      { path: 'admin/governance', name: 'enterprise-governance', meta: { requiresAuth: true }, component: () => import('../views/admin/GovernanceView.vue') },
      { path: 'admin/platform', name: 'enterprise-platform', meta: { requiresAuth: true }, component: () => import('../views/admin/PlatformView.vue') },
      { path: 'bi/kpis', name: 'bi-kpis', meta: { requiresAuth: true }, component: () => import('../views/bi/KPIManagementView.vue') },
      { path: 'bi/dashboards', name: 'bi-dashboards', meta: { requiresAuth: true }, component: () => import('../views/bi/DashboardBuilderView.vue') },
      { path: 'bi/view/:id', name: 'bi-view', meta: { requiresAuth: true }, component: () => import('../views/bi/DashboardViewerView.vue') },
      { path: 'bi/reports', name: 'bi-reports', meta: { requiresAuth: true }, component: () => import('../views/bi/ReportBuilderView.vue') },
      { path: 'bi/forecasting', name: 'bi-forecasting', meta: { requiresAuth: true }, component: () => import('../views/bi/ForecastingView.vue') },
      { path: 'manufacturing/bom', name: 'mfg-bom', meta: { requiresAuth: true }, component: () => import('../views/manufacturing/BOMView.vue') },
      { path: 'manufacturing/orders', name: 'mfg-orders', meta: { requiresAuth: true }, component: () => import('../views/manufacturing/ManufacturingOrdersView.vue') },
      { path: 'manufacturing/qc', name: 'mfg-qc', meta: { requiresAuth: true }, component: () => import('../views/manufacturing/QCInspectionView.vue') },
      { path: 'manufacturing/shopfloor', name: 'mfg-shopfloor', meta: { requiresAuth: true }, component: () => import('../views/manufacturing/ShopfloorView.vue') },
      { path: 'planning', name: 'production-plans', meta: { requiresAuth: true }, component: () => import('../views/planning/ProductionPlansView.vue') },
      { path: 'planning/resources', name: 'resource-planning', meta: { requiresAuth: true }, component: () => import('../views/planning/ResourcePlanningView.vue') },
      { path: 'hr/attendance', name: 'hr-attendance', meta: { requiresAuth: true }, component: () => import('../views/hr/AttendanceView.vue') },
      { path: 'hr/leaves', name: 'hr-leaves', meta: { requiresAuth: true }, component: () => import('../views/hr/LeaveRequestsView.vue') },
      { path: 'hr/payroll', name: 'hr-payroll', meta: { requiresAuth: true }, component: () => import('../views/hr/PayrollView.vue') },
      { path: 'hr/timesheets', name: 'hr-timesheets', meta: { requiresAuth: true }, component: () => import('../views/hr/TimesheetsView.vue') },
      { path: 'hr/jobs', name: 'hr-jobs', meta: { requiresAuth: true }, component: () => import('../views/hr/JobOpeningsView.vue') },
      { path: 'hr/candidates', name: 'hr-candidates', meta: { requiresAuth: true }, component: () => import('../views/hr/JobCandidatesView.vue') },
      { path: 'projects', name: 'projects', meta: { requiresAuth: true }, component: () => import('../views/projects/ProjectsView.vue') },
      { path: 'projects/tasks', name: 'project-tasks', meta: { requiresAuth: true }, component: () => import('../views/projects/TasksView.vue') },
      { path: 'projects/milestones', name: 'project-milestones', meta: { requiresAuth: true }, component: () => import('../views/projects/MilestonesView.vue') },
      { path: 'projects/contracts', name: 'contracts', meta: { requiresAuth: true }, component: () => import('../views/projects/ContractsView.vue') },
      { path: 'projects/documents', name: 'documents', meta: { requiresAuth: true }, component: () => import('../views/projects/DocumentsView.vue') },
      { path: 'maintenance/assets', name: 'maintenance-assets', meta: { requiresAuth: true }, component: () => import('../views/maintenance/AssetsView.vue') },
      { path: 'maintenance/schedules', name: 'maintenance-schedules', meta: { requiresAuth: true }, component: () => import('../views/maintenance/SchedulesView.vue') },
      { path: 'maintenance/work-orders', name: 'maintenance-work-orders', meta: { requiresAuth: true }, component: () => import('../views/maintenance/WorkOrdersView.vue') },
      { path: 'integrations', name: 'integrations', meta: { requiresAuth: true }, component: () => import('../views/integrations/IntegrationsView.vue') },
      { path: 'integrations/ecommerce', name: 'integrations-ecommerce', meta: { requiresAuth: true }, component: () => import('../views/integrations/EcommerceView.vue') },
      { path: 'integrations/api', name: 'integrations-api', meta: { requiresAuth: true }, component: () => import('../views/integrations/ApiPlatformView.vue') },
      { path: ':pathMatch(.*)*', name: 'not-found', component: () => import('../views/errors/NotFoundView.vue') },
    ]
  },
  { path: '/:pathMatch(.*)*', name: 'not-found-root', component: () => import('../views/errors/NotFoundView.vue') },
]

const router = createRouter({ history: createWebHistory(), routes })

router.beforeEach((to, from, next) => {
  const token = localStorage.getItem('nova_token')
  const auth = useAuthStore()

  if (to.meta.requiresAuth && !token) return next('/login')
  if (token && (to.name === 'login' || to.name === 'signup')) return next('/dashboard')

  const required = ROUTE_PERMISSIONS[to.name]
  if (required) {
    if (!auth.hasPermission(required)) return next('/dashboard')
  }

  next()
})

export default router
