import os
import re
import logging
from typing import Optional
from packages.database.connection import get_connection, release_connection

logger = logging.getLogger(__name__)

# Standard document sequence mappings
DOCUMENT_SEQUENCES = {
    'invoice': 'seq_invoice_number',
    'pick_list': 'seq_pick_list_number',
}

# Standard document prefix mappings
DOCUMENT_PREFIXES = {
    'invoice': 'INV',
    'pick_list': 'PKL',
}


def _qualify_sequence_name(sequence_name: str, schema: Optional[str] = None) -> str:
    """Format and qualify sequence name with schema if needed."""
    if '.' in sequence_name:
        return sequence_name
    target_schema = schema or os.getenv('DB_SCHEMA', 'Nova')
    clean_seq = sequence_name.strip('"')
    if target_schema:
        clean_schema = target_schema.strip('"')
        return f'"{clean_schema}"."{clean_seq}"'
    return f'"{clean_seq}"'


def _extract_int_value(row) -> int:
    """Extract integer value from cursor fetchone result regardless of cursor factory."""
    if isinstance(row, dict):
        return int(list(row.values())[0])
    elif isinstance(row, (tuple, list)):
        return int(row[0])
    return int(row)


def get_next_sequence_value(sequence_name: str, conn=None, schema: Optional[str] = None) -> int:
    """
    Atomically get the next value from a PostgreSQL sequence.

    Args:
        sequence_name: Name of the sequence (e.g. 'seq_invoice_number')
        conn: Optional existing database connection (e.g. within transaction)
        schema: Optional schema name (defaults to DB_SCHEMA or 'Nova')

    Returns:
        The next integer value generated by PostgreSQL nextval()
    """
    qualified_seq = _qualify_sequence_name(sequence_name, schema)
    should_release = False

    if conn is None:
        conn = get_connection()
        should_release = True

    try:
        with conn.cursor() as cur:
            cur.execute("SELECT nextval(%s)", (qualified_seq,))
            row = cur.fetchone()
            if not row:
                raise RuntimeError(f"Failed to fetch next value for sequence '{qualified_seq}'")
            return _extract_int_value(row)
    except Exception as e:
        logger.error(f"Error obtaining next sequence value for '{qualified_seq}': {e}")
        raise
    finally:
        if should_release:
            release_connection(conn)


def generate_document_number(
    sequence_name: str,
    prefix: str = "",
    padding: int = 5,
    conn=None,
    schema: Optional[str] = None,
) -> str:
    """
    Generate a formatted, sequential document number backed by a PostgreSQL sequence.

    Args:
        sequence_name: Name of the PostgreSQL sequence
        prefix: Prefix for the document (e.g. 'INV', 'PKL', 'INV-')
        padding: Number of digits to pad (default: 5)
        conn: Optional database connection
        schema: Optional schema name

    Returns:
        Formatted document number string (e.g. 'INV-00001', 'PKL-00042')
    """
    seq_val = get_next_sequence_value(sequence_name, conn=conn, schema=schema)
    formatted_num = f"{seq_val:0{padding}d}"

    if not prefix:
        return formatted_num
    if prefix.endswith('-'):
        return f"{prefix}{formatted_num}"
    return f"{prefix}-{formatted_num}"


def generate_invoice_number(
    conn=None,
    schema: Optional[str] = None,
    prefix: str = "INV",
    padding: int = 5,
) -> str:
    """
    Generate the next concurrency-safe invoice number (e.g. INV-00001).
    """
    seq_name = DOCUMENT_SEQUENCES.get('invoice', 'seq_invoice_number')
    return generate_document_number(
        sequence_name=seq_name,
        prefix=prefix,
        padding=padding,
        conn=conn,
        schema=schema,
    )


def generate_pick_list_number(
    conn=None,
    schema: Optional[str] = None,
    prefix: str = "PKL",
    padding: int = 5,
) -> str:
    """
    Generate the next concurrency-safe pick list number (e.g. PKL-00001).
    """
    seq_name = DOCUMENT_SEQUENCES.get('pick_list', 'seq_pick_list_number')
    return generate_document_number(
        sequence_name=seq_name,
        prefix=prefix,
        padding=padding,
        conn=conn,
        schema=schema,
    )


def set_sequence_value(
    sequence_name: str,
    value: int,
    is_called: bool = True,
    conn=None,
    schema: Optional[str] = None,
) -> int:
    """
    Set / synchronize a PostgreSQL sequence value.
    """
    qualified_seq = _qualify_sequence_name(sequence_name, schema)
    should_release = False

    if conn is None:
        conn = get_connection()
        should_release = True

    try:
        with conn.cursor() as cur:
            cur.execute("SELECT setval(%s, %s, %s)", (qualified_seq, value, is_called))
            row = cur.fetchone()
            return _extract_int_value(row)
    finally:
        if should_release:
            release_connection(conn)


def reset_sequence(
    sequence_name: str,
    start_val: int = 1,
    conn=None,
    schema: Optional[str] = None,
) -> int:
    """
    Reset a PostgreSQL sequence to start_val.
    """
    return set_sequence_value(
        sequence_name=sequence_name,
        value=start_val,
        is_called=False,
        conn=conn,
        schema=schema,
    )


def get_current_sequence_value(
    sequence_name: str,
    conn=None,
    schema: Optional[str] = None,
) -> int:
    """
    Get the last allocated / current value of a PostgreSQL sequence.
    """
    qualified_seq = _qualify_sequence_name(sequence_name, schema)
    should_release = False

    if conn is None:
        conn = get_connection()
        should_release = True

    try:
        with conn.cursor() as cur:
            # Query sequence relation directly for last_value
            cur.execute(f"SELECT last_value FROM {qualified_seq}")
            row = cur.fetchone()
            if not row:
                raise RuntimeError(f"Could not retrieve last value for sequence '{qualified_seq}'")
            return _extract_int_value(row)
    finally:
        if should_release:
            release_connection(conn)
