window.app = {
  modules: {},
  current: null,
  _started: false,

  nav: [
    { section: 'Foundation' },
    { id: 'home', icon: 'home', label: 'Home', module: 'home', permission: 'DASHBOARD_VIEW' },
    { id: 'dashboard', icon: 'dashboard', label: 'Dashboard', module: 'dashboard', permission: 'DASHBOARD_VIEW' },
    { id: 'pos', icon: 'point_of_sale', label: 'POS', module: 'pos', permission: 'POS_VIEW' },
    { id: 'products', icon: 'inventory_2', label: 'Products', module: 'products', permission: 'PRODUCTS_VIEW' },
    { id: 'inventory', icon: 'warehouse', label: 'Inventory', module: 'inventory', permission: 'INVENTORY_VIEW' },
    { id: 'warehouse', icon: 'factory', label: 'Warehouse', module: 'warehouse', permission: 'WAREHOUSE_VIEW' },
    { section: 'CRM & Procurement' },
    { id: 'leads', icon: 'person_search', label: 'Leads', module: 'leads', permission: 'CUSTOMERS_VIEW' },
    { id: 'opportunities', icon: 'trending_up', label: 'Opportunities', module: 'opportunities', permission: 'CUSTOMERS_VIEW' },
    { id: 'customers', icon: 'group', label: 'Customers', module: 'customers', permission: 'CUSTOMERS_VIEW' },
    { id: 'suppliers', icon: 'local_shipping', label: 'Suppliers', module: 'suppliers', permission: 'SUPPLIERS_VIEW' },
    { id: 'purchasing', icon: 'receipt_long', label: 'Purchasing', module: 'purchasing', permission: 'PURCHASING_VIEW' },
    { id: 'purchase_requisitions', icon: 'description', label: 'Requisitions', module: 'purchase_requisitions', permission: 'PURCHASING_VIEW' },
    { id: 'rfqs', icon: 'rate_review', label: 'RFQs', module: 'rfqs', permission: 'PURCHASING_VIEW' },
    { id: 'goods_receipt', icon: 'inventory_2', label: 'Goods Receipt', module: 'goods_receipt', permission: 'WAREHOUSE_VIEW' },
    { id: 'purchase_returns', icon: 'assignment_returned', label: 'Purchase Returns', module: 'purchase_returns', permission: 'PURCHASING_VIEW' },
    { id: 'delivery', icon: 'local_shipping', label: 'Delivery', module: 'delivery', permission: 'SALES_VIEW' },
    { id: 'tax_rates', icon: 'percent', label: 'Tax Rates', module: 'tax_rates', permission: 'SALES_VIEW' },
    { id: 'sales_returns', icon: 'assignment_return', label: 'Sales Returns', module: 'sales_returns', permission: 'SALES_VIEW' },
    { id: 'sales', icon: 'payments', label: 'Sales', module: 'sales', permission: 'SALES_VIEW' },
    { id: 'serial_numbers', icon: 'qr_code', label: 'Serial Numbers', module: 'serial_numbers', permission: 'WAREHOUSE_VIEW' },
    { id: 'batch_numbers', icon: 'inventory_2', label: 'Batch Numbers', module: 'batch_numbers', permission: 'WAREHOUSE_VIEW' },
    { id: 'price_lists', icon: 'attach_money', label: 'Price Lists', module: 'price_lists', permission: 'SALES_VIEW' },
    { id: 'quotations', icon: 'request_quote', label: 'Quotations', module: 'quotations', permission: 'SALES_VIEW' },
    { id: 'invoices', icon: 'receipt', label: 'Invoices', module: 'invoices', permission: 'FINANCE_VIEW' },
    { id: 'payments', icon: 'payments', label: 'Payments', module: 'payments', permission: 'FINANCE_VIEW' },
    { id: 'chart_of_accounts', icon: 'account_balance', label: 'Chart of Accounts', module: 'chart_of_accounts', permission: 'FINANCE_VIEW' },
    { id: 'journal_entries', icon: 'book', label: 'Journal Entries', module: 'journal_entries', permission: 'FINANCE_VIEW' },
    { id: 'finance', icon: 'account_balance', label: 'Finance', module: 'finance', permission: 'FINANCE_VIEW' },
    { id: 'settings', icon: 'settings', label: 'Settings', module: 'settings', permission: 'ADMIN_VIEW' },
    { id: 'admin', icon: 'admin_panel_settings', label: 'Admin', module: 'admin', permission: 'ADMIN_VIEW' },
    { id: 'module_manager', icon: 'extension', label: 'Modules', module: 'module_manager', permission: 'ADMIN_VIEW' },
    { section: 'Platform Infrastructure' },
    { id: 'notifications', icon: 'notifications', label: 'Notifications', module: 'notifications', permission: 'ADMIN_VIEW' },
    { id: 'scheduled_tasks', icon: 'schedule', label: 'Scheduled Tasks', module: 'scheduled_tasks', permission: 'ADMIN_VIEW' },
    { id: 'audit_log', icon: 'history', label: 'Audit Log', module: 'audit_log', permission: 'ADMIN_VIEW' },
    { section: 'Manufacturing' },
    { id: 'manufacturing', icon: 'precision_manufacturing', label: 'Manufacturing', module: 'manufacturing', permission: 'MFG_VIEW' },
    { id: 'planning', icon: 'calendar_month', label: 'Planning', module: 'planning', permission: 'PLANNING_VIEW' },
    { id: 'shopfloor', icon: 'construction', label: 'Shop Floor', module: 'shopfloor', permission: 'SHOPFLOOR_VIEW' },
    { id: 'quality', icon: 'fact_check', label: 'Quality', module: 'quality', permission: 'QUALITY_VIEW' },
    { section: 'HR Management' },
    { id: 'hr', icon: 'badge', label: 'HRMS', module: 'hr', permission: 'HR_VIEW' },
    { id: 'attendance', icon: 'schedule', label: 'Attendance', module: 'attendance', permission: 'HR_VIEW' },
    { id: 'leave', icon: 'beach_access', label: 'Leave', module: 'leave', permission: 'HR_VIEW' },
    { id: 'payroll', icon: 'payments', label: 'Payroll', module: 'payroll', permission: 'HR_VIEW' },
    { id: 'recruitment', icon: 'person_search', label: 'Recruitment', module: 'recruitment', permission: 'HR_VIEW' },
    { section: 'Maintenance' },
    { id: 'maintenance', icon: 'build', label: 'Maintenance', module: 'maintenance', permission: 'MAINTENANCE_VIEW' },
    { section: 'Projects & Services' },
    { id: 'project', icon: 'assignment', label: 'Projects', module: 'project', permission: 'PROJECTS_VIEW' },
    { id: 'resource', icon: 'groups', label: 'Resources', module: 'resource', permission: 'PROJECTS_VIEW' },
    { id: 'timesheets', icon: 'timer', label: 'Timesheets', module: 'timesheets', permission: 'PROJECTS_VIEW' },
    { id: 'service', icon: 'support_agent', label: 'Service', module: 'service', permission: 'PROJECTS_VIEW' },
    { id: 'contracts', icon: 'description', label: 'Contracts', module: 'contracts', permission: 'PROJECTS_VIEW' },
    { section: 'BI & Analytics' },
    { id: 'bi', icon: 'analytics', label: 'BI', module: 'bi', permission: 'BI_VIEW' },
    { id: 'executive', icon: 'dashboard_customize', label: 'Executive', module: 'executive', permission: 'BI_VIEW' },
    { id: 'operational', icon: 'insights', label: 'Operations', module: 'operational', permission: 'BI_VIEW' },
    { id: 'forecast', icon: 'trending_up', label: 'Forecast', module: 'forecast', permission: 'BI_VIEW' },
    { id: 'insights', icon: 'lightbulb', label: 'Insights', module: 'insights', permission: 'BI_VIEW' },
    { section: 'Mobile & E-Commerce' },
    { id: 'mobile', icon: 'phone_android', label: 'Mobile', module: 'mobile', permission: 'INTEGRATIONS_VIEW' },
    { id: 'mobilepos', icon: 'smartphone', label: 'Mobile POS', module: 'mobilepos', permission: 'INTEGRATIONS_VIEW' },
    { id: 'ecommerce', icon: 'shopping_cart', label: 'E-Commerce', module: 'ecommerce', permission: 'INTEGRATIONS_VIEW' },
    { id: 'integrations', icon: 'extension', label: 'Integrations', module: 'integrations', permission: 'INTEGRATIONS_VIEW' },
    { id: 'api', icon: 'api', label: 'API', module: 'api', permission: 'INTEGRATIONS_VIEW' },
    { section: 'Enterprise' },
    { id: 'tenant', icon: 'business', label: 'Tenants', module: 'tenant', permission: 'ENTERPRISE_VIEW' },
    { id: 'workflow', icon: 'alt_route', label: 'Workflow', module: 'workflow', permission: 'ENTERPRISE_VIEW' },
    { id: 'documents', icon: 'folder', label: 'Documents', module: 'documents', permission: 'ENTERPRISE_VIEW' },
    { id: 'governance', icon: 'gavel', label: 'Governance', module: 'governance', permission: 'ENTERPRISE_VIEW' },
    { id: 'platform', icon: 'cloud', label: 'Platform', module: 'platform', permission: 'ENTERPRISE_VIEW' },
  ],
}
